"""
migrar_achados.py
-----------------
Migra os registros de Achados e Perdidos do SQLite antigo
para a tabela ACHADOS_PERDIDOS no Oracle (CCTV Control Panel).

Uso:
    python migrar_achados.py

O script é idempotente por ID_REGISTRO: se um registro com o mesmo
id_registro já existir no Oracle, ele é ignorado (não duplicado).
"""

import sqlite3
import oracledb
from datetime import datetime

# ── Configurações ──────────────────────────────────────────────────────────────
SQLITE_PATH = r"C:\Users\deivimar\OneDrive - DPDHL\Documents\GitHub\Achados_perdidos\achados_perdidos.db"

ORACLE_USER     = "SECPANEL"
ORACLE_PASSWORD = "SEC003q2w3e4r2026"
ORACLE_DSN      = "usqasap023-scan.phx-dc.dhl.com:1521/SECPANEL"

# ── Conexões ───────────────────────────────────────────────────────────────────
print("Conectando ao SQLite...")
sqlite_conn = sqlite3.connect(SQLITE_PATH)
sqlite_conn.row_factory = sqlite3.Row
sqlite_cur = sqlite_conn.cursor()

print("Conectando ao Oracle...")
ora_conn = oracledb.connect(user=ORACLE_USER, password=ORACLE_PASSWORD, dsn=ORACLE_DSN)
ora_cur  = ora_conn.cursor()

# ── Garante que a tabela existe ────────────────────────────────────────────────
try:
    ora_cur.execute("""
        CREATE TABLE ACHADOS_PERDIDOS (
            ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ID_REGISTRO  NUMBER NOT NULL,
            ID_ANTERIOR  VARCHAR2(50),
            OBJETO       VARCHAR2(200) NOT NULL,
            RESPONSAVEL  VARCHAR2(150) NOT NULL,
            DATA         VARCHAR2(20) NOT NULL,
            TURNO        NUMBER NOT NULL,
            DESCRICAO    CLOB,
            FOTO_PATH    VARCHAR2(500),
            STATUS       VARCHAR2(30) DEFAULT 'Pendente',
            RETIRADO_POR VARCHAR2(150),
            SITE         VARCHAR2(128),
            CRIADO_POR   VARCHAR2(120),
            CREATED_AT   TIMESTAMP DEFAULT SYSTIMESTAMP
        )
    """)
    ora_conn.commit()
    print("Tabela ACHADOS_PERDIDOS criada.")
except oracledb.DatabaseError as e:
    if "ORA-00955" in str(e) or "already exists" in str(e).lower():
        print("Tabela ACHADOS_PERDIDOS já existe — OK.")
    else:
        print(f"Aviso ao criar tabela: {e}")

# ── Lê registros existentes no Oracle (para evitar duplicatas) ─────────────────
ora_cur.execute("SELECT ID_REGISTRO FROM ACHADOS_PERDIDOS")
ja_migrados = {row[0] for row in ora_cur.fetchall()}
print(f"Registros já existentes no Oracle: {len(ja_migrados)}")

# ── Lê todos os registros do SQLite ───────────────────────────────────────────
sqlite_cur.execute("SELECT * FROM achados_perdidos ORDER BY id_registro")
rows = sqlite_cur.fetchall()
print(f"Registros no SQLite: {len(rows)}")

# ── Migra ──────────────────────────────────────────────────────────────────────
INSERT_SQL = """
    INSERT INTO ACHADOS_PERDIDOS
        (ID_REGISTRO, ID_ANTERIOR, OBJETO, RESPONSAVEL, DATA, TURNO,
         DESCRICAO, FOTO_PATH, STATUS, RETIRADO_POR, SITE, CRIADO_POR, CREATED_AT)
    VALUES
        (:1, :2, :3, :4, :5, :6,
         :7, :8, :9, :10, NULL, NULL, :11)
"""

migrados  = 0
ignorados = 0

for row in rows:
    id_reg = row["id_registro"]

    if id_reg in ja_migrados:
        print(f"  SKIP  #{id_reg} — {row['objeto']} (já existe)")
        ignorados += 1
        continue

    # Converte created_at para TIMESTAMP
    try:
        created_at = datetime.fromisoformat(row["created_at"])
    except Exception:
        created_at = datetime.utcnow()

    params = (
        id_reg,
        row["id_anterior"],
        row["objeto"],
        row["responsavel"],
        row["data"],
        row["turno"],
        row["descricao"],
        row["foto_path"],
        row["status"] or "Pendente",
        row["retirado_por"],
        created_at,
    )

    try:
        ora_cur.execute(INSERT_SQL, params)
        print(f"  OK    #{id_reg} — {row['objeto']}")
        migrados += 1
    except Exception as e:
        print(f"  ERRO  #{id_reg} — {row['objeto']}: {e}")
        ora_conn.rollback()

ora_conn.commit()

# ── Resumo ─────────────────────────────────────────────────────────────────────
print()
print("=" * 50)
print(f"Migração concluída!")
print(f"  Migrados : {migrados}")
print(f"  Ignorados: {ignorados} (já existiam)")
print(f"  Total    : {len(rows)}")
print("=" * 50)

sqlite_conn.close()
ora_conn.close()
