#!/usr/bin/env python3
"""
CCTV_Updater — instalador / atualizador automático do CCTV Control Panel.

Fluxo:
  1. Conecta ao Oracle (oracledb thin mode — sem Oracle Client)
  2. Busca o release marcado como ATIVO em APP_RELEASES
  3. Baixa o EXE (BLOB) e salva em %LOCALAPPDATA%\\CCTV_ControlPanel\\
  4. Grava version.txt com a versão instalada
  5. Cria / atualiza atalho na Area de Trabalho
  5. Abre o app se --open ou se o usuario marcou o checkbox
"""

import os
import sys
import subprocess
import threading
import argparse
import ctypes
import tkinter as tk
from tkinter import ttk, messagebox

import oracledb

# ─── Credenciais do banco ─────────────────────────────────────────────────────
_DB_USER    = "SECPANEL"
_DB_PASS    = "SEC003q2w3e4r2026"
_DB_HOST    = "usqasap023-scan.phx-dc.dhl.com"
_DB_PORT    = 1521
_DB_SERVICE = "SECPANEL"

# ─── Caminhos ────────────────────────────────────────────────────────────────
# Estrutura one-folder:
#   %LOCALAPPDATA%\CCTV_ControlPanel\        ← raiz (persiste entre updates)
#     ├── app\                               ← pasta do PyInstaller (trocada a cada update)
#     │   └── CCTV_ControlPanel.exe
#     ├── version.txt
#     └── cctv_error.log
INSTALL_ROOT     = os.path.join(
    os.environ.get("LOCALAPPDATA", os.path.expanduser("~")),
    "CCTV_ControlPanel"
)
APP_DIR          = os.path.join(INSTALL_ROOT, "app")
APP_EXE_NAME     = "CCTV_ControlPanel.exe"
APP_EXE          = os.path.join(APP_DIR, APP_EXE_NAME)
VERSION_FILE     = os.path.join(INSTALL_ROOT, "version.txt")
APP_DISPLAY_NAME = "CCTV Control Panel"

# Compat: nome antigo usado em outros pontos
INSTALL_DIR      = INSTALL_ROOT

# ─── Cores ───────────────────────────────────────────────────────────────────
C_RED    = "#d40511"
C_RED_DK = "#b1030d"
C_BG     = "#f3f5f7"
C_WHITE  = "#ffffff"
C_TEXT   = "#1f2937"
C_MUTED  = "#6b7280"
C_LINE   = "#e5e7eb"
C_GREEN  = "#16a34a"
C_GREEN_BG = "#dcfce7"
C_WARN   = "#92400e"
C_WARN_BG = "#fffbeb"


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _desktop_path() -> str:
    try:
        buf = ctypes.create_unicode_buffer(512)
        ctypes.windll.shell32.SHGetFolderPathW(None, 0x0010, None, 0, buf)
        if buf.value:
            return buf.value
    except Exception:
        pass
    return os.path.join(os.path.expanduser("~"), "Desktop")


def _start_menu_path() -> str:
    """Pasta Programas do Menu Iniciar do usuário."""
    try:
        buf = ctypes.create_unicode_buffer(512)
        # CSIDL_PROGRAMS = 0x0002 (Menu Iniciar > Programas do usuário)
        ctypes.windll.shell32.SHGetFolderPathW(None, 0x0002, None, 0, buf)
        if buf.value:
            return buf.value
    except Exception:
        pass
    return os.path.join(
        os.environ.get("APPDATA", os.path.expanduser("~")),
        "Microsoft", "Windows", "Start Menu", "Programs",
    )


def _create_shortcut(target: str, shortcut_lnk: str, description: str = "") -> None:
    t   = target.replace("'", "''")
    lnk = shortcut_lnk.replace("'", "''")
    dsc = description.replace("'", "''")
    wd  = os.path.dirname(target).replace("'", "''")
    ps  = (
        f"$ws = New-Object -ComObject WScript.Shell; "
        f"$s = $ws.CreateShortcut('{lnk}'); "
        f"$s.TargetPath = '{t}'; "
        f"$s.WorkingDirectory = '{wd}'; "
        f"$s.Description = '{dsc}'; "
        f"$s.Save()"
    )
    subprocess.run(
        ["powershell", "-NoProfile", "-NonInteractive", "-WindowStyle", "Hidden",
         "-Command", ps],
        capture_output=True,
    )


def _fmt_bytes(n: int) -> str:
    if n < 1024:        return f"{n} B"
    if n < 1024 ** 2:   return f"{n / 1024:.1f} KB"
    return f"{n / 1024 ** 2:.1f} MB"


def _local_version() -> str:
    """Lê a versão instalada localmente (version.txt). Retorna '—' se não encontrada."""
    try:
        if os.path.exists(VERSION_FILE):
            return open(VERSION_FILE, encoding="utf-8").read().strip()
    except Exception:
        pass
    # app\ (novo) ou raiz (instalação legada one-file)
    if os.path.exists(APP_EXE) or os.path.exists(os.path.join(INSTALL_ROOT, APP_EXE_NAME)):
        return "instalado (versão desconhecida)"
    return "não instalado"


def _db_connect():
    """Abre conexão Oracle thin e garante que APP_RELEASES existe."""
    oracledb.defaults.fetch_lobs = False
    dsn  = oracledb.makedsn(_DB_HOST, _DB_PORT, service_name=_DB_SERVICE)
    conn = oracledb.connect(user=_DB_USER, password=_DB_PASS, dsn=dsn)
    cur  = conn.cursor()
    try:
        cur.execute(
            "CREATE TABLE APP_RELEASES ("
            "  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            "  VERSAO VARCHAR2(20) NOT NULL,"
            "  NOME_ARQUIVO VARCHAR2(255),"
            "  TAMANHO_BYTES NUMBER,"
            "  EXE_BLOB BLOB,"
            "  PUBLICADO_EM TIMESTAMP DEFAULT SYSTIMESTAMP,"
            "  PUBLICADO_POR VARCHAR2(120),"
            "  ATIVO VARCHAR2(1) DEFAULT 'N'"
            ")"
        )
        conn.commit()
    except oracledb.DatabaseError:
        pass   # já existe
    cur.close()
    return conn


# ─── Verificar versão (leve — sem download) ───────────────────────────────────

def _do_check(on_result, on_error):
    try:
        conn = _db_connect()
        cur  = conn.cursor()
        cur.execute(
            "SELECT VERSAO, TAMANHO_BYTES, PUBLICADO_EM, PUBLICADO_POR FROM "
            "(SELECT VERSAO, TAMANHO_BYTES, PUBLICADO_EM, PUBLICADO_POR "
            " FROM APP_RELEASES WHERE ATIVO = 'S' ORDER BY PUBLICADO_EM DESC) "
            "WHERE ROWNUM = 1"
        )
        row = cur.fetchone()
        cur.close()
        conn.close()

        local_ver  = _local_version()
        server_ver = row[0] if row else None
        tamanho    = row[1] if row else None
        pub_em     = row[2] if row else None
        pub_por    = row[3] if row else None

        on_result(local_ver, server_ver, tamanho, pub_em, pub_por)
    except Exception as exc:
        on_error(str(exc))


# ─── Instalação ───────────────────────────────────────────────────────────────

def _do_install(on_status, on_progress, on_done, on_error, open_after=False):
    import io
    import zipfile
    import shutil
    try:
        on_status("Conectando ao servidor...")
        on_progress(5)
        conn = _db_connect()

        on_status("Verificando versao disponivel...")
        on_progress(12)
        cur = conn.cursor()
        cur.execute(
            "SELECT VERSAO, NOME_ARQUIVO, EXE_BLOB FROM "
            "(SELECT VERSAO, NOME_ARQUIVO, EXE_BLOB FROM APP_RELEASES "
            " WHERE ATIVO = 'S' ORDER BY PUBLICADO_EM DESC) "
            "WHERE ROWNUM = 1"
        )
        row = cur.fetchone()
        cur.close()
        conn.close()

        if not row:
            raise RuntimeError(
                "Nenhuma versao ativa encontrada no servidor.\n\n"
                "O administrador precisa publicar um release em:\n"
                "Administracao > Releases > Publicar nova versao."
            )

        versao, nome_arquivo, blob = row
        nome_arquivo = nome_arquivo or ""
        if not blob:
            raise RuntimeError(
                f"O arquivo da versao {versao} esta vazio no servidor.\n"
                "Contate o administrador."
            )

        on_status(f"Versao {versao} ({_fmt_bytes(len(blob))}) — baixando...")
        on_progress(45)
        os.makedirs(INSTALL_ROOT, exist_ok=True)

        # ZIP (pacote one-folder) vs EXE (legado one-file) — detecta pela assinatura
        is_zip = blob[:4] == b"PK\x03\x04" or nome_arquivo.lower().endswith(".zip")

        if is_zip:
            app_new = os.path.join(INSTALL_ROOT, "app_new")
            app_old = os.path.join(INSTALL_ROOT, "app_old")
            if os.path.exists(app_new):
                shutil.rmtree(app_new, ignore_errors=True)

            on_status("Extraindo arquivos...")
            on_progress(65)
            with zipfile.ZipFile(io.BytesIO(blob)) as zf:
                zf.extractall(app_new)

            # Normaliza: se o zip tiver a pasta CCTV_ControlPanel\ por dentro, sobe o conteudo
            if not os.path.exists(os.path.join(app_new, APP_EXE_NAME)):
                subdirs = [d for d in os.listdir(app_new)
                           if os.path.isdir(os.path.join(app_new, d))]
                for d in subdirs:
                    if os.path.exists(os.path.join(app_new, d, APP_EXE_NAME)):
                        sub = os.path.join(app_new, d)
                        tmp = app_new + "_inner"
                        shutil.rmtree(tmp, ignore_errors=True)
                        shutil.move(sub, tmp)
                        shutil.rmtree(app_new, ignore_errors=True)
                        shutil.move(tmp, app_new)
                        break

            if not os.path.exists(os.path.join(app_new, APP_EXE_NAME)):
                shutil.rmtree(app_new, ignore_errors=True)
                raise RuntimeError(
                    "Pacote invalido: CCTV_ControlPanel.exe nao encontrado no .zip."
                )

            on_status("Aplicando atualizacao...")
            on_progress(82)
            # Swap seguro: app -> app_old, app_new -> app, com rollback
            if os.path.exists(app_old):
                shutil.rmtree(app_old, ignore_errors=True)
            if os.path.exists(APP_DIR):
                try:
                    os.rename(APP_DIR, app_old)
                except OSError:
                    shutil.rmtree(app_new, ignore_errors=True)
                    raise RuntimeError(
                        "Nao foi possivel atualizar (arquivos em uso).\n\n"
                        "Feche o CCTV Control Panel e tente novamente."
                    )
            try:
                os.rename(app_new, APP_DIR)
            except OSError:
                if os.path.exists(app_old) and not os.path.exists(APP_DIR):
                    os.rename(app_old, APP_DIR)   # rollback
                shutil.rmtree(app_new, ignore_errors=True)
                raise RuntimeError("Falha ao aplicar a atualizacao. Tente novamente.")
            shutil.rmtree(app_old, ignore_errors=True)
            install_path = APP_EXE
        else:
            # Legado: o blob é o proprio EXE → grava direto em app\
            os.makedirs(APP_DIR, exist_ok=True)
            install_path = APP_EXE
            if os.path.exists(install_path):
                try:
                    os.remove(install_path)
                except PermissionError:
                    raise RuntimeError(
                        f"Nao foi possivel substituir:\n{install_path}\n\n"
                        "Feche o CCTV Control Panel e tente novamente."
                    )
            with open(install_path, "wb") as f:
                f.write(blob)

        # Grava version.txt na raiz (persiste entre updates)
        with open(VERSION_FILE, "w", encoding="utf-8") as f:
            f.write(versao)
        on_progress(90)

        # Remove EXE legado solto na raiz (migracao do modelo one-file antigo)
        _legacy = os.path.join(INSTALL_ROOT, APP_EXE_NAME)
        if os.path.exists(_legacy):
            try:
                os.remove(_legacy)
            except Exception:
                pass

        on_status("Criando atalhos (Area de Trabalho e Menu Iniciar)...")
        on_progress(95)
        _create_shortcut(install_path,
                         os.path.join(_desktop_path(), f"{APP_DISPLAY_NAME}.lnk"),
                         APP_DISPLAY_NAME)
        _sm = _start_menu_path()
        try:
            os.makedirs(_sm, exist_ok=True)
        except Exception:
            pass
        _create_shortcut(install_path,
                         os.path.join(_sm, f"{APP_DISPLAY_NAME}.lnk"),
                         APP_DISPLAY_NAME)

        on_progress(100)
        on_status(f"Versao {versao} instalada com sucesso!")
        on_done(versao, install_path, open_after)

    except Exception as exc:
        on_error(str(exc))


# ─── Interface gráfica ────────────────────────────────────────────────────────

class UpdaterUI:
    W, H = 500, 340

    def __init__(self, open_after_default: bool = False):
        self.root = tk.Tk()
        self.root.title("CCTV Control Panel — Instalador")
        self.root.resizable(False, False)
        self.root.configure(bg=C_BG)

        # Centralizar
        self.root.update_idletasks()
        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        x  = (sw - self.W) // 2
        y  = (sh - self.H) // 2
        self.root.geometry(f"{self.W}x{self.H}+{x}+{y}")

        self._running = False
        self._build_ui(open_after_default)

    # ── Construção da UI ───────────────────────────────────────

    def _build_ui(self, open_after_default):
        # ── Cabeçalho vermelho ──────────────────────────────────
        hdr = tk.Frame(self.root, bg=C_RED, height=60)
        hdr.pack(fill=tk.X)
        hdr.pack_propagate(False)
        tk.Label(
            hdr, text="  CCTV Control Panel — Instalador",
            bg=C_RED, fg=C_WHITE,
            font=("Arial", 13, "bold"), anchor="w",
        ).pack(fill=tk.X, padx=18, pady=16)

        # ── Painel de versões ───────────────────────────────────
        ver_frame = tk.Frame(self.root, bg=C_WHITE,
                             highlightbackground=C_LINE, highlightthickness=1)
        ver_frame.pack(fill=tk.X, padx=20, pady=(14, 0))

        # linha: Local
        row_local = tk.Frame(ver_frame, bg=C_WHITE)
        row_local.pack(fill=tk.X, padx=14, pady=(10, 4))
        tk.Label(row_local, text="Instalada:", bg=C_WHITE, fg=C_MUTED,
                 font=("Arial", 9, "bold"), width=10, anchor="w").pack(side=tk.LEFT)
        self.lbl_ver_local = tk.Label(row_local, text=_local_version(),
                                      bg=C_WHITE, fg=C_TEXT,
                                      font=("Arial", 9, "bold"), anchor="w")
        self.lbl_ver_local.pack(side=tk.LEFT)

        # linha: Servidor
        row_server = tk.Frame(ver_frame, bg=C_WHITE)
        row_server.pack(fill=tk.X, padx=14, pady=(0, 10))
        tk.Label(row_server, text="Servidor:", bg=C_WHITE, fg=C_MUTED,
                 font=("Arial", 9, "bold"), width=10, anchor="w").pack(side=tk.LEFT)
        self.lbl_ver_server = tk.Label(row_server, text="—",
                                       bg=C_WHITE, fg=C_MUTED,
                                       font=("Arial", 9, "bold"), anchor="w")
        self.lbl_ver_server.pack(side=tk.LEFT)

        # ── Corpo ───────────────────────────────────────────────
        body = tk.Frame(self.root, bg=C_BG)
        body.pack(fill=tk.BOTH, expand=True, padx=20, pady=14)

        self.lbl_status = tk.Label(
            body,
            text="Pronto. Use os botoes abaixo para instalar ou verificar.",
            bg=C_BG, fg=C_TEXT,
            font=("Arial", 9), anchor="w",
            wraplength=450, justify="left",
        )
        self.lbl_status.pack(fill=tk.X, pady=(0, 8))

        self.progress = ttk.Progressbar(body, maximum=100, mode="determinate")
        self.progress.pack(fill=tk.X, pady=(0, 12))
        try:
            s = ttk.Style()
            s.theme_use("clam")
            s.configure("TProgressbar", troughcolor=C_LINE,
                         background=C_RED, thickness=10)
        except Exception:
            pass

        # Checkbox abrir após instalar
        self.var_open = tk.BooleanVar(value=open_after_default)
        tk.Checkbutton(
            body,
            text="Abrir o CCTV Control Panel apos a instalacao",
            variable=self.var_open,
            bg=C_BG, fg=C_TEXT,
            activebackground=C_BG,
            font=("Arial", 9),
            cursor="hand2",
        ).pack(anchor="w", pady=(0, 12))

        # ── Linha de botões ─────────────────────────────────────
        sep = tk.Frame(self.root, bg=C_LINE, height=1)
        sep.pack(fill=tk.X)

        btn_bar = tk.Frame(self.root, bg=C_WHITE)
        btn_bar.pack(fill=tk.X, padx=20, pady=12)

        # Instalar
        self.btn_instalar = tk.Button(
            btn_bar,
            text="▶  Instalar / Atualizar",
            bg=C_RED, fg=C_WHITE,
            font=("Arial", 10, "bold"),
            relief=tk.FLAT, cursor="hand2",
            padx=16, pady=7,
            command=self._start_install,
        )
        self.btn_instalar.pack(side=tk.LEFT)

        # Verificar versão
        self.btn_check = tk.Button(
            btn_bar,
            text="🔍  Verificar versao",
            bg="#e0f2fe", fg="#0369a1",
            font=("Arial", 10),
            relief=tk.FLAT, cursor="hand2",
            padx=14, pady=7,
            command=self._start_check,
        )
        self.btn_check.pack(side=tk.LEFT, padx=(8, 0))

        # Abrir pasta
        tk.Button(
            btn_bar,
            text="📁  Abrir pasta",
            bg=C_LINE, fg=C_TEXT,
            font=("Arial", 10),
            relief=tk.FLAT, cursor="hand2",
            padx=14, pady=7,
            command=self._abrir_pasta,
        ).pack(side=tk.LEFT, padx=(8, 0))

        # Fechar (direita)
        tk.Button(
            btn_bar,
            text="Fechar",
            bg=C_LINE, fg=C_MUTED,
            font=("Arial", 10),
            relief=tk.FLAT, cursor="hand2",
            padx=14, pady=7,
            command=self.root.destroy,
        ).pack(side=tk.RIGHT)

    # ── Ações ──────────────────────────────────────────────────

    def _set_status(self, msg: str):
        self.root.after(0, lambda: self.lbl_status.config(text=msg))

    def _set_progress(self, pct: int):
        self.root.after(0, lambda: self.progress.config(value=pct))

    def _lock(self):
        self.btn_instalar.config(state=tk.DISABLED)
        self.btn_check.config(state=tk.DISABLED)

    def _unlock(self):
        self.btn_instalar.config(state=tk.NORMAL)
        self.btn_check.config(state=tk.NORMAL)

    # ── Instalar ───────────────────────────────────────────────

    def _start_install(self):
        if self._running:
            return
        self._running = True
        self._lock()
        self._set_progress(0)
        threading.Thread(
            target=_do_install,
            args=(self._set_status, self._set_progress,
                  self._on_install_done, self._on_install_error,
                  self.var_open.get()),
            daemon=True,
        ).start()

    def _on_install_done(self, versao: str, install_path: str, open_after: bool):
        def _cb():
            self._running = False
            self._unlock()
            self.btn_instalar.config(text="✔  Instalado")
            # Atualiza painel de versão
            self.lbl_ver_local.config(text=versao, fg=C_GREEN)
            if open_after:
                self.root.after(1000, lambda: [
                    subprocess.Popen([install_path]),
                    self.root.destroy(),
                ])
            else:
                messagebox.showinfo(
                    "Instalacao concluida",
                    f"Versao {versao} instalada com sucesso!\n\n"
                    f"Local: {install_path}\n"
                    "Atalhos criados na Area de Trabalho e no Menu Iniciar.",
                )
        self.root.after(0, _cb)

    def _on_install_error(self, msg: str):
        def _cb():
            self._running = False
            self._unlock()
            self._set_status("Erro durante a instalacao.")
            self._set_progress(0)
            messagebox.showerror("Erro na instalacao", msg)
        self.root.after(0, _cb)

    # ── Verificar versão ────────────────────────────────────────

    def _start_check(self):
        if self._running:
            return
        self._running = True
        self._lock()
        self._set_status("Consultando servidor...")
        self._set_progress(0)
        threading.Thread(
            target=_do_check,
            args=(self._on_check_done, self._on_check_error),
            daemon=True,
        ).start()

    def _on_check_done(self, local_ver, server_ver, tamanho, pub_em, pub_por):
        def _cb():
            self._running = False
            self._unlock()
            self._set_progress(0)

            # Atualiza painel
            if server_ver:
                cor = C_GREEN if local_ver == server_ver else C_WARN
                self.lbl_ver_server.config(text=server_ver, fg=cor)
                self.lbl_ver_local.config(
                    fg=C_GREEN if local_ver == server_ver else C_RED
                )

            # Monta mensagem do dialog
            if not server_ver:
                msg = (
                    "Nenhuma versao ativa no servidor.\n\n"
                    "Contate o administrador para publicar um release."
                )
                messagebox.showwarning("Verificacao de versao", msg)
                self._set_status("Nenhuma versao ativa no servidor.")
                return

            tam_str = _fmt_bytes(tamanho) if tamanho else "—"
            pub_str = pub_em.strftime("%d/%m/%Y %H:%M") if pub_em else "—"

            if local_ver == server_ver:
                status_txt = "Sistema ATUALIZADO"
                icone = "✔"
            else:
                status_txt = "Atualizacao DISPONIVEL"
                icone = "⚠"

            msg = (
                f"{icone}  {status_txt}\n\n"
                f"  Versao instalada :  {local_ver}\n"
                f"  Versao no servidor:  {server_ver}\n"
                f"  Tamanho          :  {tam_str}\n"
                f"  Publicado em     :  {pub_str}\n"
                f"  Publicado por    :  {pub_por or '—'}\n"
            )
            if local_ver == server_ver:
                messagebox.showinfo("Verificacao de versao", msg)
                self._set_status(f"Versao {server_ver} — sistema atualizado.")
            else:
                resp = messagebox.askyesno(
                    "Atualizacao disponivel",
                    msg + "\n\nDeseja instalar agora?",
                )
                if resp:
                    self._set_status("Iniciando instalacao...")
                    self._start_install()
                else:
                    self._set_status(
                        f"Versao local: {local_ver}  |  Servidor: {server_ver}"
                    )

        self.root.after(0, _cb)

    def _on_check_error(self, msg: str):
        def _cb():
            self._running = False
            self._unlock()
            self._set_progress(0)
            self._set_status("Erro ao consultar servidor.")
            messagebox.showerror("Erro na verificacao", msg)
        self.root.after(0, _cb)

    # ── Abrir pasta ─────────────────────────────────────────────

    def _abrir_pasta(self):
        os.makedirs(INSTALL_ROOT, exist_ok=True)
        subprocess.Popen(["explorer", INSTALL_ROOT])

    # ────────────────────────────────────────────────────────────

    def run(self):
        self.root.mainloop()


# ─── Modo silencioso (--auto) ─────────────────────────────────────────────────

def _run_auto(open_after: bool) -> None:
    done_evt  = threading.Event()
    exit_code = [0]

    def st(msg): print(msg, flush=True)
    def pr(pct):
        bar = "█" * (pct // 5) + "░" * (20 - pct // 5)
        print(f"\r  [{bar}] {pct:3d}%", end="", flush=True)

    def on_done(versao, path, oa):
        print(f"\n\n  Versao {versao} instalada em: {path}")
        if oa:
            subprocess.Popen([path])
        done_evt.set()

    def on_error(msg):
        print(f"\n\n  Erro: {msg}", file=sys.stderr)
        exit_code[0] = 1
        done_evt.set()

    threading.Thread(
        target=_do_install,
        args=(st, pr, on_done, on_error, open_after),
        daemon=True,
    ).start()
    done_evt.wait(timeout=600)
    sys.exit(exit_code[0])


# ─── Entry point ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CCTV Control Panel Installer")
    parser.add_argument("--open", dest="open_after", action="store_true",
                        help="Abrir o app apos instalar")
    parser.add_argument("--auto", action="store_true",
                        help="Modo silencioso sem interface grafica")
    args = parser.parse_args()

    if args.auto:
        _run_auto(open_after=args.open_after)
    else:
        UpdaterUI(open_after_default=args.open_after).run()
